/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Utilities.SetColor;
import Utilities.SetSize;
import java.awt.CardLayout;
import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class FormTrangChu extends javax.swing.JFrame {

    final private SetSize setsize = new SetSize();
    final private SetColor setcolor = new SetColor();

    /**
     * Creates new form FormTrangChu
     */
    public FormTrangChu() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setFrmChinh(new ViewBanHang());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnTrangChu1 = new javax.swing.JPanel();
        lblTrangChu1 = new javax.swing.JLabel();
        btnKhacHhang = new javax.swing.JPanel();
        lblKhachHang = new javax.swing.JLabel();
        btnBanHang = new javax.swing.JPanel();
        lblBanHang = new javax.swing.JLabel();
        btnHoaDon = new javax.swing.JPanel();
        lblHoaDon = new javax.swing.JLabel();
        btnSanPham = new javax.swing.JPanel();
        lblSanPham = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JPanel();
        lblDangXuat = new javax.swing.JLabel();
        btnKhuyenMai1 = new javax.swing.JPanel();
        lblKhuyenMai1 = new javax.swing.JLabel();
        btnThongKe = new javax.swing.JPanel();
        lblThongKe = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblNhanVien = new javax.swing.JLabel();
        FormDiff = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("BEE SPORTS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, -1));

        btnTrangChu1.setBackground(new java.awt.Color(51, 204, 0));
        btnTrangChu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTrangChu1MousePressed(evt);
            }
        });

        lblTrangChu1.setText("Trang Chủ");

        javax.swing.GroupLayout btnTrangChu1Layout = new javax.swing.GroupLayout(btnTrangChu1);
        btnTrangChu1.setLayout(btnTrangChu1Layout);
        btnTrangChu1Layout.setHorizontalGroup(
            btnTrangChu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTrangChu1Layout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addComponent(lblTrangChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnTrangChu1Layout.setVerticalGroup(
            btnTrangChu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTrangChu1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(btnTrangChu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 230, 40));

        btnKhacHhang.setBackground(new java.awt.Color(51, 204, 0));
        btnKhacHhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKhacHhangMousePressed(evt);
            }
        });

        lblKhachHang.setText("Khách Hàng");

        javax.swing.GroupLayout btnKhacHhangLayout = new javax.swing.GroupLayout(btnKhacHhang);
        btnKhacHhang.setLayout(btnKhacHhangLayout);
        btnKhacHhangLayout.setHorizontalGroup(
            btnKhacHhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnKhacHhangLayout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addComponent(lblKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnKhacHhangLayout.setVerticalGroup(
            btnKhacHhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(btnKhacHhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 40));

        btnBanHang.setBackground(new java.awt.Color(51, 204, 0));
        btnBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBanHangMousePressed(evt);
            }
        });
        btnBanHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnBanHangKeyTyped(evt);
            }
        });

        lblBanHang.setText("Bán Hàng");

        javax.swing.GroupLayout btnBanHangLayout = new javax.swing.GroupLayout(btnBanHang);
        btnBanHang.setLayout(btnBanHangLayout);
        btnBanHangLayout.setHorizontalGroup(
            btnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBanHangLayout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addComponent(lblBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnBanHangLayout.setVerticalGroup(
            btnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(btnBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, 40));

        btnHoaDon.setBackground(new java.awt.Color(51, 204, 0));
        btnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHoaDonMousePressed(evt);
            }
        });
        btnHoaDon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnHoaDonKeyTyped(evt);
            }
        });

        lblHoaDon.setText("Hóa Đơn");

        javax.swing.GroupLayout btnHoaDonLayout = new javax.swing.GroupLayout(btnHoaDon);
        btnHoaDon.setLayout(btnHoaDonLayout);
        btnHoaDonLayout.setHorizontalGroup(
            btnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHoaDonLayout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addComponent(lblHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnHoaDonLayout.setVerticalGroup(
            btnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(btnHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 230, 40));

        btnSanPham.setBackground(new java.awt.Color(51, 204, 0));
        btnSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSanPhamMousePressed(evt);
            }
        });

        lblSanPham.setText("Sản Phẩm");

        javax.swing.GroupLayout btnSanPhamLayout = new javax.swing.GroupLayout(btnSanPham);
        btnSanPham.setLayout(btnSanPhamLayout);
        btnSanPhamLayout.setHorizontalGroup(
            btnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSanPhamLayout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addComponent(lblSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnSanPhamLayout.setVerticalGroup(
            btnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(btnSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 230, 40));

        btnDangXuat.setBackground(new java.awt.Color(51, 204, 0));
        btnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDangXuatMousePressed(evt);
            }
        });

        lblDangXuat.setText("Đăng Xuất");

        javax.swing.GroupLayout btnDangXuatLayout = new javax.swing.GroupLayout(btnDangXuat);
        btnDangXuat.setLayout(btnDangXuatLayout);
        btnDangXuatLayout.setHorizontalGroup(
            btnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDangXuatLayout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addComponent(lblDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnDangXuatLayout.setVerticalGroup(
            btnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 230, 40));

        btnKhuyenMai1.setBackground(new java.awt.Color(51, 204, 0));
        btnKhuyenMai1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKhuyenMai1MousePressed(evt);
            }
        });

        lblKhuyenMai1.setText("Khuyến Mại");

        javax.swing.GroupLayout btnKhuyenMai1Layout = new javax.swing.GroupLayout(btnKhuyenMai1);
        btnKhuyenMai1.setLayout(btnKhuyenMai1Layout);
        btnKhuyenMai1Layout.setHorizontalGroup(
            btnKhuyenMai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnKhuyenMai1Layout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addComponent(lblKhuyenMai1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnKhuyenMai1Layout.setVerticalGroup(
            btnKhuyenMai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKhuyenMai1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(btnKhuyenMai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 230, 40));

        btnThongKe.setBackground(new java.awt.Color(51, 204, 0));
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnThongKeMousePressed(evt);
            }
        });

        lblThongKe.setText("Thống Kê");

        javax.swing.GroupLayout btnThongKeLayout = new javax.swing.GroupLayout(btnThongKe);
        btnThongKe.setLayout(btnThongKeLayout);
        btnThongKeLayout.setHorizontalGroup(
            btnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnThongKeLayout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(lblThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnThongKeLayout.setVerticalGroup(
            btnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 230, 40));

        jPanel3.setBackground(new java.awt.Color(0, 204, 51));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        lblNhanVien.setText("Nhân viên");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addComponent(lblNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 230, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 670));

        FormDiff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(FormDiff, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1190, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrangChu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChu1MousePressed
        // TODO add your handling code here:
        this.setFrmChinh(new ClockPanel());
        this.setcolor.changeColorBtn("Trang chủ", getBtn());
    }//GEN-LAST:event_btnTrangChu1MousePressed

    private void btnBanHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanHangMousePressed
        try {
            // TODO add your handling code here:
            this.setFrmChinh(new ViewBanHang());
        } catch (SQLException ex) {
            Logger.getLogger(FormTrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setcolor.changeColorBtn("Bán hàng", getBtn());
    }//GEN-LAST:event_btnBanHangMousePressed

    private void btnDangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangXuatMousePressed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất không?", "bạn chắc chứ?", JOptionPane.YES_NO_OPTION);
        if (choice == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnDangXuatMousePressed

    private void btnHoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMousePressed
        // TODO add your handling code here:
        this.setFrmChinh(new ViewHoaDons());
        this.setcolor.changeColorBtn("Hóa đơn", getBtn());
    }//GEN-LAST:event_btnHoaDonMousePressed

    private void btnKhacHhangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhacHhangMousePressed
        // TODO add your handling code here:
        this.setFrmChinh(new KhachHangView());
        this.setcolor.changeColorBtn("Khách hàng", getBtn());
    }//GEN-LAST:event_btnKhacHhangMousePressed

    private void btnBanHangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBanHangKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBanHangKeyTyped

    private void btnHoaDonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnHoaDonKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHoaDonKeyTyped

    private void btnKhuyenMai1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhuyenMai1MousePressed
        // TODO add your handling code here:
        this.setFrmChinh(new KhuyenMaiView());
        this.setcolor.changeColorBtn("Khuyến Mãi", getBtn());
    }//GEN-LAST:event_btnKhuyenMai1MousePressed

    private void btnSanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanPhamMousePressed
        // TODO add your handling code here:
         this.setFrmChinh(new QuanLySanPham());
        this.setcolor.changeColorBtn("Sản phẩm", getBtn());
    }//GEN-LAST:event_btnSanPhamMousePressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        this.setFrmChinh(new NhanVienView());
        this.setcolor.changeColorBtn("Nhân viên", getBtn());
    }//GEN-LAST:event_jPanel3MousePressed

    private void btnThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMousePressed
        // TODO add your handling code here:
         this.setFrmChinh(new DoanhThuView());
        this.setcolor.changeColorBtn("Doanh thu", getBtn());
    }//GEN-LAST:event_btnThongKeMousePressed

    public void setFrmChinh(Component frmSet) {
        FormDiff.removeAll();
        FormDiff.setLayout(new CardLayout(0, 0));
        FormDiff.add(frmSet);
        FormDiff.revalidate();
        FormDiff.repaint();
    }

    private JLabel[] getBtn() {
        final JLabel[] _lstCN = {lblBanHang, lblDangXuat, lblHoaDon, lblKhachHang,
            lblKhuyenMai1, lblNhanVien, lblSanPham, lblTrangChu1,lblThongKe};
        return _lstCN;
    }
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormTrangChu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel FormDiff;
    private javax.swing.JPanel btnBanHang;
    private javax.swing.JPanel btnDangXuat;
    private javax.swing.JPanel btnHoaDon;
    private javax.swing.JPanel btnKhacHhang;
    private javax.swing.JPanel btnKhuyenMai1;
    private javax.swing.JPanel btnSanPham;
    private javax.swing.JPanel btnThongKe;
    private javax.swing.JPanel btnTrangChu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBanHang;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblKhuyenMai1;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblSanPham;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblTrangChu1;
    // End of variables declaration//GEN-END:variables
}
