/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Domainmodel.KhachHang;
import Service.KhachHangImpl;
import ServiceImpl.KhachHangService;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phuong Bi
 */
public class KhachHangView extends javax.swing.JPanel {
 private KhachHangImpl khachHangService = new KhachHangService();
    
    DefaultTableModel model = new DefaultTableModel();
    
    public void loadTable() {
        ArrayList<KhachHang> k = khachHangService.getAll();
        model = (DefaultTableModel) tbbang.getModel();
        
        model.setColumnCount(0);
        model.addColumn("ID");
        model.addColumn("Ma");
        model.addColumn("Ten");
        model.addColumn("Gioi tinh");
        model.addColumn("Dia chi");
        model.addColumn("Ngay sinh");        
        model.addColumn("Dien thoai");
        
        model.setRowCount(0);
        for (KhachHang khachHang : k) {
            model.addRow(new Object[]{
                khachHang.getId(), khachHang.getMa(), khachHang.getTen(),
                khachHang.getGioiTinh(), khachHang.getDiaChi(), khachHang.getNgaySinh(),
                khachHang.getDienThoai()});
            
        }
    }
    /**
     * Creates new form KhachHangView
     */
    public KhachHangView() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        txtmaKH = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdiaChi = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txttenKH = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbbang2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtdienThoai = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnsua = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnlamMoi = new javax.swing.JButton();
        rdonam = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtngaySinh = new javax.swing.JTextField();
        rdonu = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        txtdiaChi.setColumns(20);
        txtdiaChi.setRows(5);
        jScrollPane1.setViewportView(txtdiaChi);

        jLabel2.setText("Họ tên");

        tbbang2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbbang2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbbang2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbbang2);

        jLabel3.setText("Điện thoại");

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jLabel4.setText("Địa chỉ");

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        jLabel5.setText("Ngày sinh");

        btnlamMoi.setText("Xóa");
        btnlamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlamMoiActionPerformed(evt);
            }
        });

        rdonam.setText("Nam");

        jLabel7.setText("Trạng thái");

        jLabel6.setText("Tìm kiếm");

        rdonu.setText("Nữ");

        jLabel1.setText("Mã KH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(btnthem)
                .addGap(161, 161, 161)
                .addComponent(btnsua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlamMoi)
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txttenKH))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtmaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdonam)
                                .addGap(45, 45, 45)
                                .addComponent(rdonu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtdienThoai)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtdienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txttenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdonam)
                            .addComponent(rdonu)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnlamMoi))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbbang2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbbang2MouseClicked
        // TODO add your handling code here:
        int index = tbbang.getSelectedRow();
        String ns = tbbang.getValueAt(index, 5).toString();
        String gioiTinh = tbbang.getValueAt(index, 3).toString();

        // Date ngay = Date.valueOf(ngaySinh);

        txtmaKH.setText(tbbang.getValueAt(index, 1).toString());
        txttenKH.setText(tbbang.getValueAt(index, 2).toString());

        txtdiaChi.setText(tbbang.getValueAt(index, 4).toString());
        txtdienThoai.setText(tbbang.getValueAt(index, 6).toString());
        if (gioiTinh.equals("Nam")) {
            rdonam.setSelected(true);
        } else {
            rdonu.setSelected(true);
        }

        txtngaySinh.setText(tbbang.getValueAt(index, 5).toString());

    }//GEN-LAST:event_tbbang2MouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:

        KhachHang kh = new KhachHang();

        kh.setMa(txtmaKH.getText());
        kh.setTen(txttenKH.getText());
        kh.setDiaChi(txtdiaChi.getText());
        kh.setDienThoai(txtdienThoai.getText());
        kh.setNgaySinh(txtngaySinh.getText());
        if (rdonam.isSelected()) {
            kh.setGioiTinh("Nam");
        } else {
            kh.setGioiTinh("Nữ");
        }
        kh.setTrangThai("1");

        boolean kt = khachHangService.add(kh);
        if (kt == true) {
            JOptionPane.showMessageDialog(this, "Them thanh cong");
            loadTable();
        } else {
            JOptionPane.showMessageDialog(this, "Them that bai");
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:

        KhachHang kh = new KhachHang();

        kh.setMa(txtmaKH.getText());
        kh.setTen(txttenKH.getText());
        kh.setDiaChi(txtdiaChi.getText());
        kh.setDienThoai(txtdienThoai.getText());
        kh.setNgaySinh(txtngaySinh.getText());
        if (rdonam.isSelected()) {
            kh.setGioiTinh("Nam");
        } else {
            kh.setGioiTinh("Nữ");
        }
        kh.setTrangThai("1");

        boolean kt = khachHangService.update(txtmaKH.getText(), kh);
        if (kt == true) {
            JOptionPane.showMessageDialog(this, "Sua thanh cong");
            loadTable();
        } else {
            JOptionPane.showMessageDialog(this, "Sua that bai");
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnlamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlamMoiActionPerformed
        // TODO add your handling code here:
        boolean kt = khachHangService.delete(txtmaKH.getText());
        if (kt == true) {
            JOptionPane.showMessageDialog(this, "Xóa thanh cong");
            loadTable();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa that bai");
        }
    }//GEN-LAST:event_btnlamMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlamMoi;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JRadioButton rdonam;
    private javax.swing.JRadioButton rdonu;
    private javax.swing.JTable tbbang;
    private javax.swing.JTable tbbang1;
    private javax.swing.JTable tbbang2;
    private javax.swing.JTextArea txtdiaChi;
    private javax.swing.JTextField txtdienThoai;
    private javax.swing.JTextField txtmaKH;
    private javax.swing.JTextField txtngaySinh;
    private javax.swing.JTextField txttenKH;
    // End of variables declaration//GEN-END:variables
}
