/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Domainmodel.KhachHang;
import Service.KhachHangImpl;
import ServiceImpl.KhachHangService;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phuong Bi
 */
public class KhachHangView extends javax.swing.JPanel {

    private KhachHangImpl khachHangService = new KhachHangService();

    DefaultTableModel model = new DefaultTableModel();

    public void loadTable() {
        ArrayList<KhachHang> list = khachHangService.getAll();
        model = (DefaultTableModel) tbbangKhachHang.getModel();
        model.setColumnCount(0);
        model.addColumn("Id");
        model.addColumn("Mã");
        model.addColumn("Tên");
        model.addColumn("Giới tính");
        model.addColumn("Địa chỉ");
        model.addColumn("Ngày sinh");
        model.addColumn("Điện thoại");
        model.addColumn("Email");
        model.addColumn("Thành phố");

        model.setRowCount(0);
        for (KhachHang khachHang : list) {
            model.addRow(new Object[]{
                khachHang.getId(),
                khachHang.getMa(),
                khachHang.getTen(),
                khachHang.getGioiTinh(),
                khachHang.getDiaChi(),
                khachHang.getNgaySinh(),
                khachHang.getDienThoai(),
                khachHang.getEmail(),
                khachHang.getThanhPho()
            });

        }

    }
    
     public void loadTableLocGioiTinh(String gioiTinh) {
        ArrayList<KhachHang> list = khachHangService.locTheoGioiTinh(gioiTinh);
        model = (DefaultTableModel) tbbangKhachHang.getModel();
        model.setColumnCount(0);
        model.addColumn("Id");
        model.addColumn("Mã");
        model.addColumn("Tên");
        model.addColumn("Giới tính");
        model.addColumn("Địa chỉ");
        model.addColumn("Ngày sinh");
        model.addColumn("Điện thoại");
        model.addColumn("Email");
        model.addColumn("Thành phố");

        model.setRowCount(0);
        for (KhachHang khachHang : list) {
            model.addRow(new Object[]{
                khachHang.getId(),
                khachHang.getMa(),
                khachHang.getTen(),
                khachHang.getGioiTinh(),
                khachHang.getDiaChi(),
                khachHang.getNgaySinh(),
                khachHang.getDienThoai(),
                khachHang.getEmail(),
                khachHang.getThanhPho()
            });

        }

    }
    
      public void loadTableTimKiemTen(String ten) {
        ArrayList<KhachHang> list = khachHangService.timKiemTheoTen(ten);
        model = (DefaultTableModel) tbbangKhachHang.getModel();
        model.setColumnCount(0);
        model.addColumn("Id");
        model.addColumn("Mã");
        model.addColumn("Tên");
        model.addColumn("Giới tính");
        model.addColumn("Địa chỉ");
        model.addColumn("Ngày sinh");
        model.addColumn("Điện thoại");
        model.addColumn("Email");
        model.addColumn("Thành phố");

        model.setRowCount(0);
        for (KhachHang khachHang : list) {
            model.addRow(new Object[]{
                khachHang.getId(),
                khachHang.getMa(),
                khachHang.getTen(),
                khachHang.getGioiTinh(),
                khachHang.getDiaChi(),
                khachHang.getNgaySinh(),
                khachHang.getDienThoai(),
                khachHang.getEmail(),
                khachHang.getThanhPho()
            });

        }

    }

    /**
     * Creates new form KhachHangView
     */
    public KhachHangView() {
        initComponents();
        loadTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    txtmaKH = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    txttenKH = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    txtdiaChi = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    rdonam = new javax.swing.JRadioButton();
    rdonu = new javax.swing.JRadioButton();
    jLabel5 = new javax.swing.JLabel();
    txtngaySinh = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    txtdienThoai = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    txtemail = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    txtthanhPho = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tbbangKhachHang = new javax.swing.JTable();
    btnthem = new javax.swing.JButton();
    btnsua = new javax.swing.JButton();
    btnxoa = new javax.swing.JButton();
    jLabel9 = new javax.swing.JLabel();
    txttimKiemTen = new javax.swing.JTextField();
    jLabel10 = new javax.swing.JLabel();
    cbblocGioiTinh = new javax.swing.JComboBox<>();

    setBackground(new java.awt.Color(51, 153, 0));

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel1.setText("Mã");

    txtmaKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel2.setText("Tên");

    txttenKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel3.setText("Địa chỉ");

    txtdiaChi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel4.setText("Giới tính");

    buttonGroup1.add(rdonam);
    rdonam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    rdonam.setText("Nam");

    buttonGroup1.add(rdonu);
    rdonu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    rdonu.setText("Nữ");

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel5.setText("Ngày sinh");

    txtngaySinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel6.setText("Điện thoại");

    txtdienThoai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));

    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel7.setText("Email");

    txtemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));

    jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel8.setText("Thành phố");

    txtthanhPho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(25, 25, 25)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel5)
          .addComponent(jLabel3)
          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(txtmaKH)
          .addComponent(txtdiaChi)
          .addComponent(txtngaySinh)
          .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
        .addGap(150, 150, 150)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel2)
              .addComponent(jLabel4))
            .addGap(24, 24, 24)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rdonam)
                .addGap(75, 75, 75)
                .addComponent(rdonu))
              .addComponent(txttenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtdienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txtthanhPho)))
            .addGap(0, 0, Short.MAX_VALUE))))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(txtmaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2)
            .addComponent(txttenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabel1))
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(txtdiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel4)
              .addComponent(rdonam)
              .addComponent(rdonu))))
        .addGap(21, 21, 21)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(txtngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6)
          .addComponent(txtdienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(31, 31, 31)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8)
          .addComponent(txtthanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(68, Short.MAX_VALUE))
    );

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));

    tbbangKhachHang.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    tbbangKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tbbangKhachHangMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tbbangKhachHang);

    btnthem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
    btnthem.setText("Thêm");
    btnthem.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
    btnthem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnthemActionPerformed(evt);
      }
    });

    btnsua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
    btnsua.setText("Sửa");
    btnsua.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
    btnsua.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnsuaActionPerformed(evt);
      }
    });

    btnxoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
    btnxoa.setText("Xóa");
    btnxoa.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
    btnxoa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnxoaActionPerformed(evt);
      }
    });

    jLabel9.setText("Tìm kiếm theo tên");

    txttimKiemTen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txttimKiemTenActionPerformed(evt);
      }
    });
    txttimKiemTen.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        txttimKiemTenKeyPressed(evt);
      }
    });

    jLabel10.setText("Lọc theo giới tính");

    cbblocGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nu" }));
    cbblocGioiTinh.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbblocGioiTinhActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(88, 88, 88)
            .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(71, 71, 71)
            .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(50, 50, 50)
            .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txttimKiemTen, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addComponent(cbblocGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(28, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(33, 33, 33)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel9)
          .addComponent(txttimKiemTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel10)
          .addComponent(cbblocGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnthem)
          .addComponent(btnsua)
          .addComponent(btnxoa))
        .addGap(34, 34, 34))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(5, 5, 5)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        
       
        KhachHang kh = new KhachHang();
        kh.setMa(txtmaKH.getText());
        kh.setTen(txttenKH.getText());
        kh.setDiaChi(txtdiaChi.getText());
        
        kh.setNgaySinh(txtngaySinh.getText());
        if(rdonam.isSelected()){
            kh.setGioiTinh("Nam");
        }else{
            kh.setGioiTinh("Nữ");
        }
        
        kh.setDienThoai(txtdienThoai.getText());
        kh.setEmail(txtemail.getText());
        kh.setThanhPho(txtthanhPho.getText());
        kh.setTrangThai(1);
        
        boolean kt = khachHangService.add(kh);
        if(kt == true) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            loadTable();
        }else{
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        
       
        
         
        
        KhachHang kh = new KhachHang();
        kh.setMa(txtmaKH.getText());
        kh.setTen(txttenKH.getText());
        kh.setDiaChi(txtdiaChi.getText());
        kh.setNgaySinh(txtngaySinh.getText());
        if(rdonam.isSelected()){
            kh.setGioiTinh("Nam");
        }else{
            kh.setGioiTinh("Nữ");
        }
        
        kh.setDienThoai(txtdienThoai.getText());
        kh.setEmail(txtemail.getText());
        kh.setThanhPho(txtthanhPho.getText());
        kh.setTrangThai(1);
        
        boolean kt = khachHangService.update(txtmaKH.getText(),kh);
        if(kt == true) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            loadTable();
        }else{
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
        
       
    }//GEN-LAST:event_btnsuaActionPerformed

    private void tbbangKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbbangKhachHangMouseClicked
        // TODO add your handling code here:
          int index = tbbangKhachHang.getSelectedRow();
        String gioiTinh = tbbangKhachHang.getValueAt(index, 3).toString();

        // Date ngay = Date.valueOf(ngaySinh);
     
        
      
            txtmaKH.setText(tbbangKhachHang.getValueAt(index, 1).toString());
            txttenKH.setText(tbbangKhachHang.getValueAt(index, 2).toString());
            
            txtdiaChi.setText(tbbangKhachHang.getValueAt(index, 4).toString());
            txtngaySinh.setText(tbbangKhachHang.getValueAt(index, 5).toString());
            
            
            txtdienThoai.setText(tbbangKhachHang.getValueAt(index, 6).toString());
            txtemail.setText(tbbangKhachHang.getValueAt(index, 7).toString());
            txtthanhPho.setText(tbbangKhachHang.getValueAt(index, 8).toString());
            
            if (gioiTinh.equals("Nam")) {
                rdonam.setSelected(true);
            } else {
                rdonu.setSelected(true);
            }
            
    }//GEN-LAST:event_tbbangKhachHangMouseClicked

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
         boolean kt = khachHangService.delete(txtmaKH.getText());
        if(kt == true) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            loadTable();
        }else{
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
        
    }//GEN-LAST:event_btnxoaActionPerformed

    private void txttimKiemTenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimKiemTenKeyPressed
        // TODO add your handling code here:
        loadTableTimKiemTen(txttimKiemTen.getText());
    }//GEN-LAST:event_txttimKiemTenKeyPressed

    private void cbblocGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbblocGioiTinhActionPerformed
        // TODO add your handling code here:
        if(cbblocGioiTinh.getSelectedItem().equals("Nam")){
            loadTableLocGioiTinh("Nam");
        }else{
             loadTableLocGioiTinh("Nu");
        }
        
    }//GEN-LAST:event_cbblocGioiTinhActionPerformed

  private void txttimKiemTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimKiemTenActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txttimKiemTenActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnsua;
  private javax.swing.JButton btnthem;
  private javax.swing.JButton btnxoa;
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JComboBox<String> cbblocGioiTinh;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JRadioButton rdonam;
  private javax.swing.JRadioButton rdonu;
  private javax.swing.JTable tbbangKhachHang;
  private javax.swing.JTextField txtdiaChi;
  private javax.swing.JTextField txtdienThoai;
  private javax.swing.JTextField txtemail;
  private javax.swing.JTextField txtmaKH;
  private javax.swing.JTextField txtngaySinh;
  private javax.swing.JTextField txttenKH;
  private javax.swing.JTextField txtthanhPho;
  private javax.swing.JTextField txttimKiemTen;
  // End of variables declaration//GEN-END:variables
}
