/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Domainmodel.ChucVu;
import Domainmodel.ChucVuu;
import Domainmodel.NhanVienn;
import Service.ChucVuService;
import Service.ChucVuuService;
import Service.NhanViennService;
import ServiceImpl.ChucVuServiceImpl;
import ServiceImpl.ChucVuuImpl;
import ServiceImpl.NhanViennServiceImpl;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phuong Bi
 */
public class NhanVienView extends javax.swing.JPanel {

    private NhanViennService nhanVienService = new NhanViennServiceImpl();
    private ChucVuuService cv = new ChucVuuImpl();
    DefaultTableModel model = new DefaultTableModel();

    public void loadTable() {
        ArrayList<NhanVienn> list = nhanVienService.getAll();
        model = (DefaultTableModel) tbbangNhanVien.getModel();
        model.setColumnCount(0);
        model.addColumn("ID");
        model.addColumn("Mã");
        model.addColumn("Tên");
        model.addColumn("Giới tính");
        model.addColumn("Địa chỉ");
        model.addColumn("Mật khẩu");
        model.addColumn("Điện thoại");
        model.addColumn("Email");
        model.addColumn("Ngày sinh");
        model.addColumn("Chức vụ");
        model.addColumn("Trạng thái");

        model.setRowCount(0);
        for (NhanVienn nhanVienn : list) {
            model.addRow(new Object[]{
                nhanVienn.getId(),
                nhanVienn.getMaNV(),
                nhanVienn.getTenNV(),
                nhanVienn.getGioiTinh(),
                nhanVienn.getDiaChi(),
                nhanVienn.getMatKhau(),
                nhanVienn.getDienThoai(),
                nhanVienn.getEmail(),
                nhanVienn.getNgaySinh(),
                nhanVienn.getIdChucVu(),
                nhanVienn.getTrangThai() == 1 ? "Đang làm" : "Nghỉ làm"
            });

        }

    }

    public void loadCBCChucVu() {
        cbbchucVu.removeAllItems();
        ArrayList<ChucVuu> list = cv.getAll();
        for (ChucVuu i : list) {
            cbbchucVu.addItem(i.getTen());

        }
    }

    public String layIDChucVu(String tenCV) {
        String idCV = null;
        ArrayList<ChucVuu> list = cv.getAll();
        for (ChucVuu chucVu : list) {
            if (chucVu.getTen().equals(tenCV)) {
                idCV = chucVu.getId();
            }

        }
        return idCV;

    }

    /**
     * Creates new form NhanVienView
     */
    public NhanVienView() {
        initComponents();
        loadTable();
        loadCBCChucVu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtmaNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttenNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdonam = new javax.swing.JRadioButton();
        rdonu = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtdiaChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtmatKhau = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdienThoai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rdodangLam = new javax.swing.JRadioButton();
        rdoNghiLam = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtngaySinh = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbbchucVu = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbbangNhanVien = new javax.swing.JTable();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnlamMoi = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(51, 153, 0));

        jLabel1.setText("Mã");

        jLabel2.setText("Tên");

        jLabel3.setText("Giới tính");

        buttonGroup1.add(rdonam);
        rdonam.setText("Nam");

        buttonGroup1.add(rdonu);
        rdonu.setText("Nữ");

        jLabel4.setText("Địa chỉ");

        jLabel5.setText("Mật khẩu");

        txtmatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatKhauActionPerformed(evt);
            }
        });

        jLabel6.setText("Điện thoại");

        jLabel7.setText("Email");

        jLabel8.setText("Trạng thái");

        buttonGroup2.add(rdodangLam);
        rdodangLam.setText("Đang làm");

        buttonGroup2.add(rdoNghiLam);
        rdoNghiLam.setText("Nghỉ làm");

        jLabel9.setText("Ngày sinh");

        jLabel10.setText("Chức vụ");

        cbbchucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(txtmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(rdonam)
                        .addGap(43, 43, 43)
                        .addComponent(rdonu))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(txtngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtmatKhau)
                                .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttenNV)
                            .addComponent(txtdiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel8)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdienThoai)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdodangLam)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoNghiLam)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbbchucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txttenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdonam)
                    .addComponent(rdonu)
                    .addComponent(jLabel4)
                    .addComponent(txtdiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtdienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(rdodangLam)
                    .addComponent(rdoNghiLam))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cbbchucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tbbangNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbbangNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbbangNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbbangNhanVien);

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnlamMoi.setText("Làm mới");
        btnlamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnthem)
                        .addGap(127, 127, 127)
                        .addComponent(btnsua)
                        .addGap(112, 112, 112)
                        .addComponent(btnlamMoi)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnlamMoi))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtmatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatKhauActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        NhanVienn nv = new NhanVienn();
        nv.setMaNV(txtmaNV.getText());
        nv.setTenNV(txttenNV.getText());
        if (rdonam.isSelected()) {
            nv.setGioiTinh("Nam");
        } else {
            nv.setGioiTinh("Nữ");
        }

        nv.setDiaChi(txtdiaChi.getText());
        nv.setMatKhau(txtmatKhau.getText());
        nv.setDienThoai(txtdienThoai.getText());
        nv.setEmail(txtemail.getText());
        nv.setNgaySinh(txtngaySinh.getText());
        nv.setTrangThai(1);
        String idCV = layIDChucVu((String) cbbchucVu.getSelectedItem());
        nv.setIdChucVu(idCV);

        boolean kt = nhanVienService.add(nv);

        if (kt == true) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            loadTable();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }

    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:

        NhanVienn nv = new NhanVienn();
        nv.setMaNV(txtmaNV.getText());
        nv.setTenNV(txttenNV.getText());
        if (rdonam.isSelected()) {
            nv.setGioiTinh("Nam");
        } else {
            nv.setGioiTinh("Nữ");
        }

        nv.setDiaChi(txtdiaChi.getText());
        nv.setMatKhau(txtmatKhau.getText());
        nv.setDienThoai(txtdienThoai.getText());
        nv.setEmail(txtemail.getText());
        nv.setNgaySinh(txtngaySinh.getText());

        if (rdodangLam.isSelected()) {
            nv.setTrangThai(1);
        } else {
            nv.setTrangThai(0);
        }
        String idCV = layIDChucVu((String) cbbchucVu.getSelectedItem());
        nv.setIdChucVu(idCV);

        boolean kt = nhanVienService.update(txtmaNV.getText(), nv);

        if (kt == true) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            loadTable();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnlamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlamMoiActionPerformed
        // TODO add your handling code here:
        txtmaNV.setText("");
        txttenNV.setText("");
        txtdiaChi.setText("");
        txtmatKhau.setText("");
        txtdienThoai.setText("");
        txtemail.setText("");
        txtngaySinh.setText("");
    }//GEN-LAST:event_btnlamMoiActionPerformed

    private void tbbangNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbbangNhanVienMouseClicked
        // TODO add your handling code here:
        int index = tbbangNhanVien.getSelectedRow();
        txtmaNV.setText(tbbangNhanVien.getValueAt(index, 1).toString());
        txttenNV.setText(tbbangNhanVien.getValueAt(index, 2).toString());
        String gioiTinh = tbbangNhanVien.getValueAt(index, 3).toString();
        
        if (gioiTinh.equals("Nam")) {
            rdonam.setSelected(true);
        } else {
            rdonu.setSelected(true);
        }
        

        txtdiaChi.setText(tbbangNhanVien.getValueAt(index, 4).toString());
        txtmatKhau.setText(tbbangNhanVien.getValueAt(index, 5).toString());
        txtdienThoai.setText(tbbangNhanVien.getValueAt(index, 6).toString());
        txtemail.setText(tbbangNhanVien.getValueAt(index, 7).toString());
        txtngaySinh.setText(tbbangNhanVien.getValueAt(index, 8).toString());
        cbbchucVu.setSelectedItem(tbbangNhanVien.getValueAt(index, 9).toString());
        String trangThai = tbbangNhanVien.getValueAt(index, 10).toString();
        if (trangThai.equals("Đang làm")) {
            rdodangLam.setSelected(true);
        } else {
            rdoNghiLam.setSelected(true);
        }
    }//GEN-LAST:event_tbbangNhanVienMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlamMoi;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbbchucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdoNghiLam;
    private javax.swing.JRadioButton rdodangLam;
    private javax.swing.JRadioButton rdonam;
    private javax.swing.JRadioButton rdonu;
    private javax.swing.JTable tbbangNhanVien;
    private javax.swing.JTextField txtdiaChi;
    private javax.swing.JTextField txtdienThoai;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmaNV;
    private javax.swing.JTextField txtmatKhau;
    private javax.swing.JTextField txtngaySinh;
    private javax.swing.JTextField txttenNV;
    // End of variables declaration//GEN-END:variables
}
