/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Domainmodel.NhanVien;
import Service.ChucVuService;
import Service.NhanVienService;
import ServiceImpl.ChucVuServiceImpl;
import ServiceImpl.NhanVienServiceImpl;
import Utilities.VietNamPattern;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import viewmodel.ChucVuviewModel;
import viewmodel.NhanVienViewModel;

/**
 *
 * @author nguye
 */
public class QuanLyNhanVien extends javax.swing.JPanel {

    NhanVienService nhan_vien_service;
    ChucVuService chuc_vu_service;
    NhanVien nhan_vien; // nhân viên đang được thao tác (CRUD) 

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien() throws Exception {
        initComponents();
        this.nhan_vien = new NhanVien();
        this.nhan_vien_service = new NhanVienServiceImpl();
        this.chuc_vu_service = new ChucVuServiceImpl();
        this.trang_thai.setModel(new DefaultComboBoxModel<String>(new String[]
            {"không còn hoạt động", "đang hoạt động"}));
        emptyText();
        
        ten.setPattern(VietNamPattern.TEN);
        ten.setErrorMsg("tên không hợp lệ");
        
        email.setPattern("^[0-9a-zA-Z.]+@[0-9a-zA-Z.]+$");
        email.setErrorMsg("emailkhoong hợp lệ");
        
        dia_chi.setPattern(VietNamPattern.DIA_CHI);
        dia_chi.setErrorMsg("địa chỉ không hợp lệ");
        
        so_dien_thoai.setPattern("[0-9]{10}");
        so_dien_thoai.setErrorMsg("số điện thoại không hợp lệ");
        this.initData();
        this.table_data.setAutoCreateRowSorter(true);
        
    }

    public void initData() throws Exception {
        NhanVienViewModel table = new NhanVienViewModel();
        table.fillData(this.nhan_vien_service.getAll());
        table_data.setModel(table.getModel());
        ChucVuviewModel cvvm = new ChucVuviewModel();
        fillLabel();
    }
    
    public void fillLabel() {
        ten_er.setText(ten.getLabel().getText());
        email_err.setText(email.getLabel().getText());
        phone_number_err.setText(so_dien_thoai.getLabel().getText());
        address_er.setText(dia_chi.getLabel().getText());
    }

    public void emptyText() {
        this.ten.setText("");
        this.ma.setText("");
        this.dia_chi.setText("");
        this.email.setText("");
        this.ngay_sinh.setText("");
        this.dia_chi.setText("");
        this.so_dien_thoai.setText("");
    }

    public void fillText(NhanVien _nv) {
        this.ma.setText(_nv.getMa());
        this.ten.setText(_nv.getTen());
        this.email.setText(_nv.getEmail());
        this.dia_chi.setText(_nv.getDiaChi());
        this.so_dien_thoai.setText(this.nhan_vien.getDienThoai());
        if (_nv.getGioiTinh().compareTo("Nam") == 0) {
            this.nam.setSelected(true);
        } else {
            this.nu.setSelected(true);
        }
        this.ngay_sinh.setDate(Instant.ofEpochMilli(_nv.getNgaySinh().getTime())
            .atZone(ZoneId.systemDefault())
            .toLocalDate());
        this.trang_thai.setSelectedIndex(this.nhan_vien.getTrangThai());
    }

    public void mappText() throws ParseException {
        this.nhan_vien.setTen(this.ten.getText());
        this.nhan_vien.setMa(this.ma.getText());
        this.nhan_vien.setEmail(this.email.getText());
        this.nhan_vien.setDiaChi(this.dia_chi.getText());
        this.nhan_vien.setDienThoai(this.so_dien_thoai.getText());
        this.nhan_vien.setGioiTinh(this.nam.isSelected() ? "Nam" : "Nữ");
        this.nhan_vien.setNgaySinh(Date.from(this.ngay_sinh.getDate()
                .atStartOfDay()
                .atZone(ZoneId.systemDefault())
                .toInstant()));
        this.nhan_vien.setTrangThai(this.trang_thai.getSelectedIndex());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jScrollPane1 = new javax.swing.JScrollPane();
    table_data = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    nam = new javax.swing.JRadioButton();
    nu = new javax.swing.JRadioButton();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    trang_thai = new javax.swing.JComboBox<>();
    ngay_sinh = new com.github.lgooddatepicker.components.DatePicker();
    jButton2 = new javax.swing.JButton();
    ma = new javax.swing.JLabel();
    ten_er = new javax.swing.JLabel();
    email_err = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    phone_number_err = new javax.swing.JLabel();
    ten = new view.login.swing.ValidateTextField();
    email = new view.login.swing.ValidateTextField();
    label1 = new java.awt.Label();
    jButton3 = new javax.swing.JButton();
    address_er = new javax.swing.JLabel();
    dia_chi = new view.login.swing.ValidateTextField();
    so_dien_thoai = new view.login.swing.ValidateTextField();

    table_data.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    table_data.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        table_dataMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(table_data);

    jLabel1.setText("mã nhân viên");

    jLabel2.setText("tên nhân viên");

    buttonGroup1.add(nam);
    nam.setSelected(true);
    nam.setText("Nam");

    buttonGroup1.add(nu);
    nu.setText("Nữ");

    jLabel3.setText("giới tính");

    jLabel4.setText("email");

    jLabel5.setText("số điện thoại");

    jLabel6.setText("trạng thái");

    jLabel7.setText("địa chỉ");

    jLabel8.setText("ngay_sinh");

    jButton1.setText("cập nhật thông tin");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    trang_thai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    jButton2.setText("đăng ký");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    ma.setText("jLabel9");

    ten_er.setText("ten");
    ten_er.setForeground(new java.awt.Color(255, 0, 0));

    email_err.setText("email");
    email_err.setForeground(new java.awt.Color(255, 0, 0));

    jLabel9.setForeground(new java.awt.Color(255, 0, 0));

    phone_number_err.setText("phone number");
    phone_number_err.setForeground(new java.awt.Color(255, 0, 0));

    ten.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tenActionPerformed(evt);
      }
    });

    email.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        emailActionPerformed(evt);
      }
    });

    label1.setAlignment(java.awt.Label.CENTER);
    label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    label1.setForeground(new java.awt.Color(0, 153, 102));
    label1.setText("Quản lý nhân viên");

    jButton3.setText("dổi mật khẩu");

    address_er.setForeground(new java.awt.Color(255, 0, 0));
    address_er.setText("dia chi");

    dia_chi.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        dia_chiActionPerformed(evt);
      }
    });

    so_dien_thoai.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        so_dien_thoaiActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1)
              .addComponent(ma, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel2))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addGap(166, 166, 166))
              .addGroup(layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(nam)
                    .addGap(18, 18, 18)
                    .addComponent(nu))
                  .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel6)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(trang_thai, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ten, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(ten_er))
            .addGap(31, 31, 31)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(email_err)
              .addComponent(jLabel4)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel8)
                .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ngay_sinh, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
            .addGap(23, 23, 23)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(so_dien_thoai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(dia_chi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel5)
                  .addComponent(phone_number_err)
                  .addComponent(address_er)
                  .addComponent(jLabel7))
                .addGap(0, 0, Short.MAX_VALUE)))))
        .addContainerGap())
      .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(24, 24, 24)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(jLabel3)
          .addComponent(jLabel1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(ma)
          .addComponent(nam)
          .addComponent(nu)
          .addComponent(dia_chi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(address_er)
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(jLabel4)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(so_dien_thoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(email_err)
              .addComponent(ten_er)
              .addComponent(phone_number_err))
            .addGap(29, 29, 29)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel6)
              .addComponent(jLabel8)
              .addComponent(jButton1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(trang_thai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ngay_sinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton2)
                .addComponent(jButton3))))
          .addGroup(layout.createSequentialGroup()
            .addGap(99, 99, 99)
            .addComponent(jLabel9)))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

    private void table_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_dataMouseClicked
        if (this.table_data.getSelectedRowCount() != 1) {
            return;
        }
        this.nhan_vien_service
                .getByMa(this.table_data
                        .getValueAt(this.table_data.getSelectedRow(), 0)
                        .toString())
                .ifPresent((o) -> {
                    this.nhan_vien = o;
                    this.fillText(this.nhan_vien);
                });
        
    }//GEN-LAST:event_table_dataMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (this.table_data.getSelectedRowCount() != 1) {
            JOptionPane.showMessageDialog(this, "hãy chọn một nhân viên trong bảng dưới trước khi update");
            return;
        }
        
        fillLabel();
        if (!ten.isResult()
                || !dia_chi.isResult()
                || !email.isResult()
                || !so_dien_thoai.isResult()) {
          JOptionPane.showMessageDialog(null, "thông tin không hợp lệ, vui lòng kiểm tra lại");
          return;
        }
        
        try {
            this.mappText();
            nhan_vien_service.update(nhan_vien).ifPresentOrElse((o) -> {
                JOptionPane.showMessageDialog(null, "cập nhật thông tin thành công");
                try {
                    this.initData();
                } catch (Exception ex) {
                    Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }, () -> {
                JOptionPane.showMessageDialog(null, "cập nhsạt thông tin thất bại");
            });
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        emptyText();
    }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
  }//GEN-LAST:event_jButton2ActionPerformed

  private void tenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_tenActionPerformed

  private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_emailActionPerformed

  private void dia_chiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dia_chiActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_dia_chiActionPerformed

  private void so_dien_thoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so_dien_thoaiActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_so_dien_thoaiActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel address_er;
  private javax.swing.ButtonGroup buttonGroup1;
  private view.login.swing.ValidateTextField dia_chi;
  private view.login.swing.ValidateTextField email;
  private javax.swing.JLabel email_err;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JScrollPane jScrollPane1;
  private java.awt.Label label1;
  private javax.swing.JLabel ma;
  private javax.swing.JRadioButton nam;
  private com.github.lgooddatepicker.components.DatePicker ngay_sinh;
  private javax.swing.JRadioButton nu;
  private javax.swing.JLabel phone_number_err;
  private view.login.swing.ValidateTextField so_dien_thoai;
  private javax.swing.JTable table_data;
  private view.login.swing.ValidateTextField ten;
  private javax.swing.JLabel ten_er;
  private javax.swing.JComboBox<String> trang_thai;
  // End of variables declaration//GEN-END:variables
}
